/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotalTopRouteImport } from './routes/total-top'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as GameHighsRouteImport } from './routes/game-highs'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as StatsMatchIdRouteImport } from './routes/stats/$matchId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as MatchMatchIdRouteImport } from './routes/match/$matchId'
import { Route as CoachesCoachIdRouteImport } from './routes/coaches/$coachId'
import { Route as StatsMatchIdAllRouteImport } from './routes/stats/$matchId/all'
import { Route as MatchMatchIdAllRouteImport } from './routes/match/$matchId/all'

const TotalTopRoute = TotalTopRouteImport.update({
  id: '/total-top',
  path: '/total-top',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const GameHighsRoute = GameHighsRouteImport.update({
  id: '/game-highs',
  path: '/game-highs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsMatchIdRoute = StatsMatchIdRouteImport.update({
  id: '/stats/$matchId',
  path: '/stats/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesCoachIdRoute = CoachesCoachIdRouteImport.update({
  id: '/$coachId',
  path: '/$coachId',
  getParentRoute: () => CoachesRoute,
} as any)
const StatsMatchIdAllRoute = StatsMatchIdAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => StatsMatchIdRoute,
} as any)
const MatchMatchIdAllRoute = MatchMatchIdAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => MatchMatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/game-highs': typeof GameHighsRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/total-top': typeof TotalTopRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/stats/$matchId': typeof StatsMatchIdRouteWithChildren
  '/players/': typeof PlayersIndexRoute
  '/match/$matchId/all': typeof MatchMatchIdAllRoute
  '/stats/$matchId/all': typeof StatsMatchIdAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/game-highs': typeof GameHighsRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/total-top': typeof TotalTopRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/stats/$matchId': typeof StatsMatchIdRouteWithChildren
  '/players': typeof PlayersIndexRoute
  '/match/$matchId/all': typeof MatchMatchIdAllRoute
  '/stats/$matchId/all': typeof StatsMatchIdAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coaches': typeof CoachesRouteWithChildren
  '/game-highs': typeof GameHighsRoute
  '/matches': typeof MatchesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/total-top': typeof TotalTopRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/match/$matchId': typeof MatchMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/stats/$matchId': typeof StatsMatchIdRouteWithChildren
  '/players/': typeof PlayersIndexRoute
  '/match/$matchId/all': typeof MatchMatchIdAllRoute
  '/stats/$matchId/all': typeof StatsMatchIdAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coaches'
    | '/game-highs'
    | '/matches'
    | '/sitemap.xml'
    | '/statistics'
    | '/total-top'
    | '/coaches/$coachId'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/stats/$matchId'
    | '/players/'
    | '/match/$matchId/all'
    | '/stats/$matchId/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coaches'
    | '/game-highs'
    | '/matches'
    | '/sitemap.xml'
    | '/statistics'
    | '/total-top'
    | '/coaches/$coachId'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/stats/$matchId'
    | '/players'
    | '/match/$matchId/all'
    | '/stats/$matchId/all'
  id:
    | '__root__'
    | '/'
    | '/coaches'
    | '/game-highs'
    | '/matches'
    | '/sitemap.xml'
    | '/statistics'
    | '/total-top'
    | '/coaches/$coachId'
    | '/match/$matchId'
    | '/players/$playerId'
    | '/stats/$matchId'
    | '/players/'
    | '/match/$matchId/all'
    | '/stats/$matchId/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachesRoute: typeof CoachesRouteWithChildren
  GameHighsRoute: typeof GameHighsRoute
  MatchesRoute: typeof MatchesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  TotalTopRoute: typeof TotalTopRoute
  MatchMatchIdRoute: typeof MatchMatchIdRouteWithChildren
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  StatsMatchIdRoute: typeof StatsMatchIdRouteWithChildren
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/total-top': {
      id: '/total-top'
      path: '/total-top'
      fullPath: '/total-top'
      preLoaderRoute: typeof TotalTopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-highs': {
      id: '/game-highs'
      path: '/game-highs'
      fullPath: '/game-highs'
      preLoaderRoute: typeof GameHighsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$matchId': {
      id: '/stats/$matchId'
      path: '/stats/$matchId'
      fullPath: '/stats/$matchId'
      preLoaderRoute: typeof StatsMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$coachId': {
      id: '/coaches/$coachId'
      path: '/$coachId'
      fullPath: '/coaches/$coachId'
      preLoaderRoute: typeof CoachesCoachIdRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/stats/$matchId/all': {
      id: '/stats/$matchId/all'
      path: '/all'
      fullPath: '/stats/$matchId/all'
      preLoaderRoute: typeof StatsMatchIdAllRouteImport
      parentRoute: typeof StatsMatchIdRoute
    }
    '/match/$matchId/all': {
      id: '/match/$matchId/all'
      path: '/all'
      fullPath: '/match/$matchId/all'
      preLoaderRoute: typeof MatchMatchIdAllRouteImport
      parentRoute: typeof MatchMatchIdRoute
    }
  }
}

interface CoachesRouteChildren {
  CoachesCoachIdRoute: typeof CoachesCoachIdRoute
}

const CoachesRouteChildren: CoachesRouteChildren = {
  CoachesCoachIdRoute: CoachesCoachIdRoute,
}

const CoachesRouteWithChildren =
  CoachesRoute._addFileChildren(CoachesRouteChildren)

interface MatchMatchIdRouteChildren {
  MatchMatchIdAllRoute: typeof MatchMatchIdAllRoute
}

const MatchMatchIdRouteChildren: MatchMatchIdRouteChildren = {
  MatchMatchIdAllRoute: MatchMatchIdAllRoute,
}

const MatchMatchIdRouteWithChildren = MatchMatchIdRoute._addFileChildren(
  MatchMatchIdRouteChildren,
)

interface StatsMatchIdRouteChildren {
  StatsMatchIdAllRoute: typeof StatsMatchIdAllRoute
}

const StatsMatchIdRouteChildren: StatsMatchIdRouteChildren = {
  StatsMatchIdAllRoute: StatsMatchIdAllRoute,
}

const StatsMatchIdRouteWithChildren = StatsMatchIdRoute._addFileChildren(
  StatsMatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachesRoute: CoachesRouteWithChildren,
  GameHighsRoute: GameHighsRoute,
  MatchesRoute: MatchesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  TotalTopRoute: TotalTopRoute,
  MatchMatchIdRoute: MatchMatchIdRouteWithChildren,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  StatsMatchIdRoute: StatsMatchIdRouteWithChildren,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
